name: Deploy FastAPI to Azure App Service

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: "docquery"  
  AZURE_RESOURCE_GROUP: "nizargroup"  
  AZURE_PLAN_NAME: "ASP-nizargroup-ad49"  
  AZURE_REGION: "Canada Central"  
  AZURE_CONTAINER_REGISTRY: "dockerrag.azurecr.io"  
 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Install Dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load Environment Variables
        working-directory: ./src  
        run: |
          echo "Loading environment variables from .env"
          export $(cat .env | xargs)

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy FastAPI App to Azure
        run: |
          # Create or update the app service with your app's configuration
          az webapp up \
            --name $AZURE_WEBAPP_NAME \
            --resource-group $AZURE_RESOURCE_GROUP \
            --plan $AZURE_PLAN_NAME \
            --location $AZURE_REGION \
            --runtime "PYTHON|3.9"  # Adjust runtime if needed

          # Optionally, you can configure App Service to pull directly from your GitHub repository:
          # az webapp deployment source config --name $AZURE_WEBAPP_NAME --resource-group $AZURE_RESOURCE_GROUP --repo-url https://github.com/<your-github-repo> --branch main --manual-integration
