name: Deploy FastAPI to Azure App Service

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: "docquery"
  AZURE_RESOURCE_GROUP: "nizargroup"
  AZURE_PLAN_NAME: "ASP-nizargroup-ad49"
  AZURE_REGION: "Canada Central"
  AZURE_CONTAINER_REGISTRY: "dockerrag.azurecr.io"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure using Azure CLI
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Build and Push Docker Image
        working-directory: ./docker
        run: |
          docker build -t $AZURE_WEBAPP_NAME .
          docker tag $AZURE_WEBAPP_NAME:latest $AZURE_CONTAINER_REGISTRY/$AZURE_WEBAPP_NAME:latest
          docker push $AZURE_CONTAINER_REGISTRY/$AZURE_WEBAPP_NAME:latest

      - name: Deploy FastAPI App
        run: |
          az webapp create \
            --resource-group $AZURE_RESOURCE_GROUP \
            --plan $AZURE_PLAN_NAME \
            --name $AZURE_WEBAPP_NAME \
            --deployment-container-image-name $AZURE_CONTAINER_REGISTRY/$AZURE_WEBAPP_NAME:latest
